Basic math calcs and chase after attack
rorychatt/SpaceCorps2 pull request #199
Opened 2023-11-19 00:11 UTC by Rostyslawn

2023-11-19 00:12 UTC, Rostyslawn commented
Базовое преследование может работать не коректно.

2023-11-19 19:47 UTC, rorychatt requested changes

2023-11-19 19:47 UTC, rorychatt commented on server/src/server/background/Alien.ts
> +            behaviour: "circular",
behaviour должет читаться из aliens.json

2023-11-19 19:47 UTC, rorychatt commented on server/src/server/background/Alien.ts
> +        let dx = Math.sqrt(((this.position.x ** 2) - (player.position.x ** 2)) - this.movement.aggroRadius ** 2);
newX

2023-11-19 19:47 UTC, rorychatt commented on server/src/server/background/Alien.ts
> +        let dx = Math.sqrt(((this.position.x ** 2) - (player.position.x ** 2)) - this.movement.aggroRadius ** 2);
const а не let

2023-11-19 19:47 UTC, rorychatt commented on server/src/server/background/Alien.ts
> +    attackBehavior(player: Player) {
не совсем понял в чем суть этой функции

2023-11-19 19:47 UTC, rorychatt commented on server/src/server/background/Alien.ts
> +            this.flyToDestination();
не уверен правильная ли тут логика

2023-11-19 19:47 UTC, rorychatt commented on server/src/server/background/Alien.ts
>      behaviour: AlienMovementBehaviour;
переименуй в movementBehaviour

2023-11-19 19:47 UTC, rorychatt commented on server/src/server/background/Alien.ts
>      behaviour: AlienMovementBehaviour;
надо будет везде так же это обновить

2023-11-19 19:47 UTC, rorychatt commented on server/src/server/background/Alien.ts
> +    maxAttackRadius: number;
думаю тут можно просто attackRadius

2023-11-19 19:47 UTC, rorychatt commented on server/src/server/background/GameServer.ts
> +                        await defenderEntity.countAgroRadius(attackerEntity);
не уверен, что агрорадиус надо считать

если атакуют пришельца, он сразу должен тут агриться на первого игрока, который уже атоковал

2023-11-19 19:47 UTC, rorychatt commented on server/src/server/background/GameServer.ts
> +                        await defenderEntity.attackBehavior(attackerEntity);
attackBehaviour нужно сразу при создании обьекта Alien читать из aliens.json

2023-11-19 19:47 UTC, rorychatt commented on server/src/server/data/aliens.json
> +            "maxAttackRadius": "5"
просто attackRadius, в остальных тоже можно обновить

2023-11-19 19:47 UTC, rorychatt commented on server/src/server/data/aliens.json
>              "behaviour": "passive",
movementBehaviour

2023-11-19 21:42 UTC, Rostyslawn commented
Названия - пофикшены, alien подергивается при преследовании - надо исправить

2023-11-19 21:44 UTC, Rostyslawn commented
Сделать преследование если alien - agressive

2023-11-22 10:26 UTC, rorychatt commented on server/src/server/background/Alien.ts
> +    async setTargetUUID(playerUUID: string) {
когда игрок телепортируется или пропадает с карты, пришелец тоже не должен на него агриться

Надо добавить логику, чтобы было потом меньше багов, где ты проверяешь currentMap название пришельца и игрока, они должны быть одинаковыми

2023-11-22 10:27 UTC, rorychatt commented on server/src/server/background/Alien.ts
> +    async setTargetUUID(playerUUID: string) {
Много где надо это проверять, можно написать функцию isOnSameMapAsAttacker() и использовать ее

2023-11-22 10:27 UTC, rorychatt commented on server/src/server/background/Alien.ts
> +        const player = await gameServer.getPlayerByUUID(playerUUID);
тут нужна тоже будет

 isOnSameMapAsAttacker()

2023-11-22 10:28 UTC, rorychatt commented on server/src/server/background/Alien.ts
> +                this.targetUUID = undefined;
надо как-то прекращать выполнение этой функции, не могу сейчас сообразить, но надо тоже убедиться что в ней ты делаешь проверку где-то  isOnSameMapAsAttacker()

2023-11-22 10:29 UTC, rorychatt commented on server/src/server/background/Alien.ts
> +        if(!this.targetUUID) this.targetUUID = attackerUUID;
Тут очень сложный момент, распиши логику словами в комментарии, будем смотреть

2023-11-22 10:29 UTC, rorychatt commented on server/src/server/background/Alien.ts
> +    giveDamageWithoutMultiplier() {
у тебя уже есть giveDamage которая и делает то, что надо

2023-11-22 10:31 UTC, rorychatt commented on server/src/server/background/GameServer.ts
> +} from "./Projectiles.js"; // тут
это не так фиксится, открой файл modifyImports.js (точно не помню как он назывался)

Посмотри как .ts компилируется в .js в папке /dist и сделай по аналогии с тем что уже есть. 
я почти уверен что функция назовалась moduifyGameImports или как-то так

2023-11-22 10:32 UTC, rorychatt commented on server/src/server/background/GameServer.ts
> +    async processAlienAttackBehavior() {
Пересмотри эту функцию, мне кажется тут что-то не так

Как будто ты всем пришельцам ставишь целью всех игроков поочередно

2023-11-22 10:35 UTC, rorychatt commented on server/src/server/background/GameServer.ts
> -                                entity._roamDestination.y >= mapHeight
напиши лучше метод в class SpaceMap или тут где-нибудь

checkIsInMapBounds() который будет проверять в границах ли энтити или нет

2023-11-22 10:36 UTC, rorychatt commented on server/src/server/background/GameServer.ts
> +                target.receiveDamage(attacker.giveDamageWithoutMultiplier(), attacker.uuid);
надо сделать класс по типу LaserProjectile только AlienProjectile, который будет принимать урон от обьекта пришельца из метода giveDamage() 

тогда потом игровой движок будет регестрировать этот прожектайл и только когда он долетит по игроку пройдет урон

2023-11-22 10:37 UTC, rorychatt commented on server/src/server/background/GameServer.ts
> +                    } // else if(projectile instanceof AlienProjectile) {
да верная логика, но не совсем понял что такое damageEvent (точнее откуда оно)

2023-11-22 10:37 UTC, rorychatt commented on server/src/server/background/Projectiles.ts
> +// export class AlienProjectile extends Projectile {
это верный код, поставь скорость как у LaserProjectile

2023-11-22 10:38 UTC, rorychatt commented on server/src/server/background/Projectiles.ts
> +export type ProjectileTypes = "LaserProjectile" | "RocketProjectile" | "AlienProjectile";
щас смотрю, с этой строкой что-то не так, как будто ее не должно было быть

2023-11-26 10:16 UTC, rorychatt approved these changes
god help us

2023-11-26 10:16 UTC, merged