whats company?
rorychatt/SpaceCorps2 pull request #211
Opened 2024-01-14 02:07 UTC by Rostyslawn

2024-01-14 02:59 UTC, Rostyslawn commented
Выбор компании работает, осталось над стилями поработать + убрать меню авторизации при выборе компании.

2024-01-14 08:48 UTC, rorychatt commented
Что ты имеешь ввиду под убрать меню авторизации при выборе компании?

Пока что я посмотрел код, мне нравится

2024-01-14 08:52 UTC, rorychatt approved these changes

2024-01-14 08:52 UTC, rorychatt commented on server/src/web/ts/gameLogic.ts
> +                const company = element.querySelector("h2")?.textContent;
уверен что это подходит?

2024-01-14 08:52 UTC, rorychatt commented on server/src/server/db/db.ts
> +    company: string;
можно в классе Player прописать export type PossibleCompanyName = 'mcc' | 'ne pomnju' | 'huj znaet'

2024-01-16 19:58 UTC, rorychatt requested changes

2024-01-16 19:58 UTC, rorychatt commented on server/src/server/background/Entity.ts
> +        super(map.name, name);
это не ломает код?

2024-01-16 19:58 UTC, rorychatt commented on server/src/server/background/GameServer.ts
> +} from "../db/db.js";
как ты сделал так, что у тебя тут импорты с .js работают? Отпишись мне в дискорде насчет этого

У остальных просто и у меня тоже ошибки вечно были

2024-01-16 19:58 UTC, rorychatt commented on server/src/server/data/spacemaps.json
> +                "name": "MCC",
название должно быть как было, то же самое и для остальных, если просто MCC то это непонятно. Думаю, стоит откатить изменения во всем этом файле

2024-01-16 19:58 UTC, rorychatt commented on server/src/server/db/db.ts
> +export function checkCompany(username: string): Promise<CompanyResult[]> {
Лучше назвать функцию getPlayerCompany

2024-01-16 19:58 UTC, rorychatt commented on server/src/server/db/db.ts
> +export async function changeCompany(username: string, company: string): Promise<void> {
changePlayerCompany(username: string, newCompanyName: string) 

Так понятнее будет остальным, попереименовывай немного

2024-01-16 19:58 UTC, rorychatt commented on server/src/server/main.ts
> +                    const playerCompany: string = returnedCompany[0].company;
Можно сделать в одну строчку, две переменные делают одно и то же

2024-01-16 19:58 UTC, rorychatt commented on server/src/server/main.ts
> +            `${username} logs into the game`
"... logged into the game"

2024-01-16 19:58 UTC, rorychatt commented on server/src/server/main.ts
> +                companyName as string
надо посмотреть почему тут типизация указана дополнительно as string 

Поидее комплилятор не должен жаловаться

2024-01-19 23:39 UTC, Rostyslawn commented on server/src/server/main.ts
> +                    const playerCompany: string = returnedCompany[0].company;
await getPlayerCompany(userCredentials.username)[0].company;
Element implicitly has an 'any' type because expression of type '0' can't be used to index type 'Promise<CompanyResult[]>'.
 Property '0' does not exist on type 'Promise<CompanyResult[]>'.
 Может я что-то не правильно сделал?

2024-01-21 10:07 UTC, rorychatt approved these changes

2024-01-21 10:07 UTC, rorychatt commented on server/src/server/db/db.ts
> +        throw error;
Это крашнет код, лучше чтобы было без throw

2024-01-21 11:14 UTC, merged